# Metadata about this component, to be used in the CMS
spec:
  structures:
    - editorial_blocks
  label: "Accordion"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  accordions:
    - title: Accordion 1
      opened: false
      editorial_blocks: [bookshop:structure:editorial_blocks]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
