# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "StyledText"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "hello"
  style: .green .label

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  style:
    type: select
    options:
      value_key: id
      values:
        - id: .green .label
          name: Green Label
        - id: .red .label
          name: Red Label
        - id: .blue .label
          name: Blue Label
        - id: .kbd
          name: Keyboard
